# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d-BgNd3DwkwZTSTHYD33NGtCrbarYVcQ
"""

import